# Generated by Django 3.2.8 on 2021-11-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anecdot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnecdotEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AnecdotText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Articale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='name of title')),
                ('text', models.TextField(verbose_name='text of title')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FunnyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MemPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgSrc', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(default='', max_length=20)),
                ('Password', models.CharField(default='', max_length=100)),
                ('AvatarSrc', models.CharField(default='', max_length=256)),
                ('Date', models.DateField(auto_now=True)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Status', models.CharField(default='', max_length=100)),
                ('FavoriteJoke', models.CharField(default='', max_length=512)),
                ('VkLink', models.CharField(default='', max_length=100)),
                ('Telegram', models.CharField(default='', max_length=100)),
                ('InstaLink', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='videoSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('articale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainPage.articale')),
            ],
        ),
    ]
