# Generated by Django 3.2.9 on 2021-11-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=100)),
                ('AvatarSrc', models.CharField(max_length=256)),
                ('Date', models.DateField(auto_now=True)),
                ('Email', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=100)),
                ('FavoriteJoke', models.CharField(max_length=512)),
                ('VkLink', models.CharField(max_length=100)),
                ('Telegram', models.CharField(max_length=100)),
                ('InstaLink', models.CharField(max_length=100)),
            ],
        ),
    ]
