# Generated by Django 3.2.8 on 2021-11-07 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='AvatarSrc',
            field=models.SlugField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.SlugField(validators=[django.core.validators.EmailValidator(message='не корректный email')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Login',
            field=models.SlugField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
