# Generated by Django 3.2.8 on 2021-11-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anecdot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnecdotEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AnecdotTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FunnyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MemPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgSrc', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='videoSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
