# Generated by Django 3.2.8 on 2021-11-26 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20211107_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='AvatarSrc',
            field=models.CharField(blank=True, default='static/img/logo.png', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(error_messages={'blank': 'пароль не может быть пустым'}, max_length=50, validators=[django.core.validators.EmailValidator(message='не корректный email')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='FavoriteJoke',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='InstaLink',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Login',
            field=models.SlugField(error_messages={'blank': 'логин не может быть пустым', 'invalid': 'логин должен состоять только из латинских букв, цифр, знаков подчеркивания или дефиса.'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(error_messages={'blank': 'пароль не может быть пустым'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Telegram',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='VkLink',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
