# Generated by Django 3.2.8 on 2021-11-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anecdot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnecdotEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AnecdotTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FunnyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MemPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgSrc', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('text', models.TextField(default='', max_length=1000)),
                ('videoSrc', models.CharField(default='', max_length=100)),
                ('imgSrc', models.CharField(default='', max_length=100)),
                ('likes', models.TextField(default='')),
                ('disLikes', models.TextField(default='')),
                ('likesCount', models.IntegerField(default=0)),
                ('disLikesCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='videoSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='AvatarSrc',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='FavoriteJoke',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='InstaLink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Login',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='Telegram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='VkLink',
            field=models.CharField(default='', max_length=100),
        ),
    ]
