# Generated by Django 3.2.8 on 2021-11-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20211127_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
